INSERT INTO USERS (LOGIN_NAME,PASSWORD,NAME,EMAIL) VALUES('admin','admin','Admin','admin@springside.org.cn');
INSERT INTO USERS (LOGIN_NAME,PASSWORD,NAME,EMAIL) VALUES('user','user','User','user@springside.org.cn');

INSERT INTO USERS (LOGIN_NAME,PASSWORD,NAME,EMAIL) VALUES('user2','user2','Jack','jack@springside.org.cn');
INSERT INTO USERS (LOGIN_NAME,PASSWORD,NAME,EMAIL) VALUES('user3','user3','Kate','kate@springside.org.cn');
INSERT INTO USERS (LOGIN_NAME,PASSWORD,NAME,EMAIL) VALUES('user4','user4','Sawyer','sawyer@springside.org.cn');
INSERT INTO USERS (LOGIN_NAME,PASSWORD,NAME,EMAIL) VALUES('user5','user5','Ben','ben@springside.org.cn');


INSERT INTO ROLES (NAME) VALUES('管理员');
INSERT INTO ROLES (NAME) VALUES('用户');

INSERT INTO AUTHORITIES (NAME,DISPLAY_NAME) VALUES('ROLE_VIEW_USER','查看用户');
INSERT INTO AUTHORITIES (NAME,DISPLAY_NAME) VALUES('ROLE_MODIFY_USER','管理用户');
INSERT INTO AUTHORITIES (NAME,DISPLAY_NAME) VALUES('ROLE_VIEW_ROLE','查看角色');
INSERT INTO AUTHORITIES (NAME,DISPLAY_NAME) VALUES('ROLE_MODIFY_ROLE','管理角色');

INSERT INTO USERS_ROLES VALUES(1,1);
INSERT INTO USERS_ROLES VALUES(1,2);
INSERT INTO USERS_ROLES VALUES(2,2);

INSERT INTO USERS_ROLES VALUES(3,2);
INSERT INTO USERS_ROLES VALUES(4,2);
INSERT INTO USERS_ROLES VALUES(5,2);
INSERT INTO USERS_ROLES VALUES(6,2);

INSERT INTO ROLES_AUTHORITIES VALUES(1,1);
INSERT INTO ROLES_AUTHORITIES VALUES(1,2);
INSERT INTO ROLES_AUTHORITIES VALUES(1,3);
INSERT INTO ROLES_AUTHORITIES VALUES(1,4);
INSERT INTO ROLES_AUTHORITIES VALUES(2,1);
INSERT INTO ROLES_AUTHORITIES VALUES(2,3);
