DROP TABLE ROLES_AUTHORITIES;
DROP TABLE USERS_ROLES;
DROP TABLE USERS;
DROP TABLE ROLES;
DROP TABLE AUTHORITIES;


CREATE TABLE USERS (
ID INTEGER PRIMARY KEY AUTO_INCREMENT,
LOGIN_NAME VARBINARY(20)  NOT NULL,
PASSWORD VARBINARY(20),
NAME VARBINARY(20),
EMAIL VARBINARY(30),
UNIQUE(LOGIN_NAME)
);

CREATE TABLE ROLES (
ID INTEGER PRIMARY KEY AUTO_INCREMENT,
NAME VARCHAR(20) NOT NULL UNIQUE
);

CREATE TABLE USERS_ROLES (
USER_ID INTEGER NOT NULL,
ROLE_ID INTEGER NOT NULL,
FOREIGN KEY (ROLE_ID) REFERENCES ROLES(ID),
FOREIGN KEY (USER_ID) REFERENCES USERS(ID)
);

CREATE TABLE AUTHORITIES (
ID INTEGER PRIMARY KEY AUTO_INCREMENT,
NAME VARCHAR(20) NOT NULL,
DISPLAY_NAME VARCHAR(20) NOT NULL
);

CREATE TABLE ROLES_AUTHORITIES (
ROLE_ID INTEGER NOT NULL,
AUTHORITY_ID INTEGER NOT NULL,
FOREIGN KEY (ROLE_ID) REFERENCES ROLES(ID),
FOREIGN KEY (AUTHORITY_ID) REFERENCES AUTHORITIES(ID)
);